# Generated by Django 5.1.2 on 2024-11-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_work_content_type_work_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='work',
            name='slug',
        ),
    ]
