from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

urlpatterns = [
    path(
        _('content/order/'),
        views.ContentOrderView.as_view(),
        name='content_order'
    ),
    path(
        _('content/<int:id>/delete/'),
        views.ContentDeleteView.as_view(),
        name='module_content_delete'
    ),
    path(
        _('create/'),
        views.CourseCreateView.as_view(),
        name='course_create'
    ),
    path(
        _('mine/'),
        views.ManageCourseListView.as_view(),
        name='manage_course_list'
    ),
    path(
        _('module/order/'),
        views.ModuleOrderView.as_view(),
        name='module_order'
    ),
    path(
        _('module/<int:module_id>/content/<model_name>/create/'),
        views.ContentCreateUpdateView.as_view(),
        name='module_content_create'
    ), 
    path(
        _('module/<int:module_id>/content/<model_name>/<id>/'),
        views.ContentCreateUpdateView.as_view(),
        name='module_content_update'
    ),
    path(
        _('module/<int:module_id>/'),
        views.ModuleContentListView.as_view(),
        name='module_content_list'
    ),
    path(
        _('subject/<slug:subject>/'),
        views.CourseListView.as_view(),
        name='course_list_subject'
    ),
    path(
        _('subject/<slug:subject>'),
        views.CourseListView.as_view(),
        name='course_list_subject'
    ),
    path(
        _('<slug:slug>/'),
        views.CourseDetailView.as_view(),
        name='course_detail'
    ),
    path(
        _('<pk>/edit/'),
        views.CourseUpdateView.as_view(),
        name='course_edit'
    ),
    path(
        _('<pk>/delete/'),
        views.CourseDeleteView.as_view(),
        name='course_delete'
    ),
    path(
        _('<pk>/module/'),
        views.CourseModuleUpdateView.as_view(),
        name='course_module_update'
    ),
    path(
        _('<pk>/work/<work_id>/'),
        views.CourseWorkDetailView.as_view(),
        name='course_work_detail'
    ),
    path(
        _('<pk>/work/'),
        views.CourseWorkListView.as_view(),
        name='course_work_list'
    ),
]